# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Personal page
tagline:          'A personal page'
description:      'Somethin something personal page.'
url:              https://cz4rs.github.io/
baseurl:          /

author:
  name:           'Cz4rs'
  url:            https://cz4rs.github.io/

paginate:         5

# Custom vars
version:          2.1.0
gems: [jekyll-paginate]

github:
  repo:           https://gitub.com
